apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "planespotter.fullname" . }}
  namespace: planespotter
  labels:
    app.kubernetes.io/name: {{ include "planespotter.name" . }}
    helm.sh/chart: {{ include "planespotter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "planespotter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "planespotter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend_image.repository }}:{{ .Values.frontend_image.tag }}"
          imagePullPolicy: {{ .Values.frontend_image.pullPolicy }}
          env:
          - name: PLANESPOTTER_API_ENDPOINT
            value: planespotter-svc
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
