---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  namespace: namespace: {{ .Values.namespace }}
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: "{{ .Values.mysql_image.repository }}:{{ .Values.mysql_image.tag }}"
        imagePullPolicy: {{ .Values.mysql_image.pullPolicy }}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "{{ .Values.storage_class.default }}"
      resources:
        requests:
          storage: 20Gi
